ENH: Mesh-to-mesh image registration Python classes, tests, examples
KitwareMedical/HASI pull request #32
Opened 2021-02-23 16:08 UTC by tbirdso

- Add Python implementation of mesh-to-mesh registration classes using ITK image registration techniques
- Add pytest modules to verify new registration classes
- Add example notebook to demonstrate new classes

2021-02-23 16:10 UTC, tbirdso commented
This PR separates functional mesh-to-mesh registration classes (`MeanSquaresRegistrar` and `DiffeoRegistrar`) along with their tests and examples from ongoing mesh-to-mesh point set registration development in [PR 29](https://github.com/KitwareMedical/HASI/pull/29).

2021-02-23 17:29 UTC, tbirdso commented
The failing checks `build-test-cxx (windows-2019)` and `build-macos-python-packages` are tracked in [Issue 30](https://github.com/KitwareMedical/HASI/issues/30) and appear to predate the proposed changes.

2021-02-24 20:32 UTC, thewtex requested changes
@tbirdso awesome!! :rocket: :man_singer: 

I will create an issue, but in another PR, we should do a little reorganizing and create a separate package out of the pure python code, `hasi` that has `itk-hasi` as a dependency.

A few minor issues noted inline.

2021-02-24 20:32 UTC, thewtex commented on examples/MeshToMeshRegistration.ipynb
> +    "# Download meshes\n",
Here we need:

```
os.makedirs('Data', exist_ok=True)
```

2021-02-24 20:32 UTC, thewtex commented on src/registration/meansquaresregistrar.py
> +import pytest
remove `import pytest`

2021-02-24 20:32 UTC, thewtex commented on src/registration/meshtomeshregistrar.py
> +import pytest
remove `import pytest`

2021-02-24 21:05 UTC, tbirdso commented
@thewtex Marking as draft again for now to add pytest to CI checks.

2021-02-25 13:30 UTC, tbirdso commented
@thewtex Marked as ready for review again. Note that this PR will add CI `build-test-python` checks for Python modules with pytest. Existing check failures are tracked in [Issue 30](https://github.com/KitwareMedical/HASI/issues/30) and predate these changes.

2021-02-25 22:00 UTC, thewtex approved these changes
@tbirdso awesome!!

2021-02-25 22:00 UTC, merged