WIP: Add `HASI` Python module
KitwareMedical/HASI pull request #34
Opened 2021-02-25 15:20 UTC by tbirdso

- Moved Python scripts into `src/hasi/hasi` module
- Added `pypackage.toml` with `flit`
- Updated pytests with new locations

This PR should remain as draft until [PR 32](https://github.com/KitwareMedical/HASI/pull/32) is approved and merged. Will close [Issue 33](https://github.com/KitwareMedical/HASI/issues/33).

2021-03-01 15:37 UTC, tbirdso commented
Check failures are already tracked in [Issue 30](https://github.com/KitwareMedical/HASI/issues/30). This PR is ready for review.

2021-03-02 20:37 UTC, thewtex requested changes
@tbirdso very nice, thanks!

Next steps:

- Add *itk-hasi* to the*hasi* package dependencies in pyproject.toml
- Move the *test/test_meshtomeshregistration.py* into *src/hasi/*, add pytest to the pypackage.toml testing dependencies, and ensure we can run *pytest* to run the test from *src/hasi*.
- Add a new workflow in *.github/workflows/* to test the *hasi* package. It should cd into the directory, install dependencies, run the tests, and build the package.

2021-03-02 20:37 UTC, thewtex commented on src/hasi/pyproject.toml
> +classifiers = ["License :: OSI Approved :: Apache Software License"]
Please add a few more classifiers from:

https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/0b64128a0ee699d35a3e4c971f748743c4d50106/setup.py#L51-L67

2021-03-03 19:55 UTC, tbirdso commented
@thewtex Ready for review. The `test-python-hasi-package` runs `pytest` successfully on `hasi` Python registration scripts.

2021-03-03 20:12 UTC, thewtex approved these changes
@tbirdso excellent! :1st_place_medal:

2021-03-03 20:12 UTC, merged