ENH: Update CI for reusable workflow, ITK 5.3.0o
KitwareMedical/HASI pull request #77
Opened 2022-12-21 14:58 UTC by thewtex

Closes #72

2022-12-21 15:09 UTC, dzenanz approved these changes

2022-12-22 14:47 UTC, tbirdso requested changes
@thewtex Thanks for getting this started. It looks like HASI depends on ITKBoneEnhancement for compilation and also on ITKIOScanco for testing, but by default these are not provided in the reusable workflow, hence CI failures. I will push an update to use the recent `itk-module-deps` parameters in the reusable workflow to accomplish this.

Note that Linux Python CI was marked as successful but wheel builds actually failed due to not finding ITKBoneEnhancement. I have opened an issue on the reusable workflow repo to track that silent failure. https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/issues/38

2022-12-22 15:07 UTC, tbirdso commented
Observed an instance of https://github.com/InsightSoftwareConsortium/ITK/issues/3795 where an ITKBoneEnhancement tag could not be checked out, trying the equivalent commit hash instead.

2022-12-22 19:37 UTC, thewtex reviewed
@tbirdso thanks!

LGTM

Let's address the testing data / Python package package failures in another PR.

2022-12-22 19:37 UTC, merged